services:
  ecm_max_bot:
    image: ecm_max_bot
    build:
      context: .
    container_name: ecm_max_bot
    env_file:
      - .env
    command: ["python", "main.py"]
    restart: always
    volumes:
     - ./temp/:/src/temp
    networks:
      - default
      - citeck_network
    depends_on:
      - redis
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: redis:7
    container_name: ecm_bot_redis
    restart: always
    networks:
      - default

networks:
  default:
    name: ecm_bot_network
    driver: bridge
  citeck_network:
    name: citeck_network_default
    external: true
